//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from DiceGrammar.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Dice.Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class DiceGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T_DIGIT_STRING=1, T_ALPHA_STRING=2, T_STRING=3, T_D=4, T_FUDGE=5, T_KEEP_HIGH=6, 
		T_KEEP_LOW=7, T_DROP_HIGH=8, T_DROP_LOW=9, T_ADVANTAGE=10, T_DISADVANTAGE=11, 
		T_REROLL=12, T_REROLL_ONCE=13, T_EXPLODE=14, T_COMPOUND=15, T_PENETRATE=16, 
		T_CRIT=17, T_FAIL=18, T_SORT_ASC=19, T_SORT_DESC=20, T_EQUALS=21, T_GREATER=22, 
		T_LESS=23, T_GREATER_EQUALS=24, T_LESS_EQUALS=25, T_NOT_EQUALS=26, T_LBRACE=27, 
		T_RBRACE=28, T_LSQUARE=29, T_RSQUARE=30, T_COMMA=31, T_DOT=32, T_LPAREN=33, 
		T_RPAREN=34, T_PLUS=35, T_MINUS=36, T_MULTIPLY=37, T_DIVIDE=38, WS=39;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T_DIGIT_STRING", "T_ALPHA_STRING", "T_STRING", "T_D", "T_FUDGE", "T_KEEP_HIGH", 
		"T_KEEP_LOW", "T_DROP_HIGH", "T_DROP_LOW", "T_ADVANTAGE", "T_DISADVANTAGE", 
		"T_REROLL", "T_REROLL_ONCE", "T_EXPLODE", "T_COMPOUND", "T_PENETRATE", 
		"T_CRIT", "T_FAIL", "T_SORT_ASC", "T_SORT_DESC", "T_EQUALS", "T_GREATER", 
		"T_LESS", "T_GREATER_EQUALS", "T_LESS_EQUALS", "T_NOT_EQUALS", "T_LBRACE", 
		"T_RBRACE", "T_LSQUARE", "T_RSQUARE", "T_COMMA", "T_DOT", "T_LPAREN", 
		"T_RPAREN", "T_PLUS", "T_MINUS", "T_MULTIPLY", "T_DIVIDE", "WS"
	};


	public DiceGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public DiceGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, "'d'", "'F'", "'kh'", "'kl'", "'dh'", "'dl'", 
		"'ad'", "'da'", "'rr'", "'ro'", "'!e'", "'!c'", "'!p'", "'cs'", "'f'", 
		"'sa'", "'sd'", "'='", "'>'", "'<'", "'>='", "'<='", null, "'{'", "'}'", 
		"'['", "']'", "','", "'.'", "'('", "')'", "'+'", "'-'", "'*'", "'/'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "T_DIGIT_STRING", "T_ALPHA_STRING", "T_STRING", "T_D", "T_FUDGE", 
		"T_KEEP_HIGH", "T_KEEP_LOW", "T_DROP_HIGH", "T_DROP_LOW", "T_ADVANTAGE", 
		"T_DISADVANTAGE", "T_REROLL", "T_REROLL_ONCE", "T_EXPLODE", "T_COMPOUND", 
		"T_PENETRATE", "T_CRIT", "T_FAIL", "T_SORT_ASC", "T_SORT_DESC", "T_EQUALS", 
		"T_GREATER", "T_LESS", "T_GREATER_EQUALS", "T_LESS_EQUALS", "T_NOT_EQUALS", 
		"T_LBRACE", "T_RBRACE", "T_LSQUARE", "T_RSQUARE", "T_COMMA", "T_DOT", 
		"T_LPAREN", "T_RPAREN", "T_PLUS", "T_MINUS", "T_MULTIPLY", "T_DIVIDE", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DiceGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static DiceGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ')', '\xC0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x3', '\x2', 
		'\x6', '\x2', 'S', '\n', '\x2', '\r', '\x2', '\xE', '\x2', 'T', '\x3', 
		'\x3', '\x3', '\x3', '\a', '\x3', 'Y', '\n', '\x3', '\f', '\x3', '\xE', 
		'\x3', '\\', '\v', '\x3', '\x3', '\x4', '\x6', '\x4', '_', '\n', '\x4', 
		'\r', '\x4', '\xE', '\x4', '`', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', 
		'\xA3', '\n', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', 
		'#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', '%', '\x3', '%', '\x3', 
		'&', '\x3', '&', '\x3', '\'', '\x3', '\'', '\x3', '(', '\x3', '(', '\x3', 
		'(', '\x3', '(', '\x2', '\x2', ')', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 
		'G', '%', 'I', '&', 'K', '\'', 'M', '(', 'O', ')', '\x3', '\x2', '\a', 
		'\x3', '\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x5', 
		'\x2', '\x32', ';', '\x43', '\\', '\x63', '|', '\a', '\x2', '*', '+', 
		']', ']', '_', '_', '}', '}', '\x7F', '\x7F', '\f', '\x2', '\v', '\xF', 
		'\"', '\"', '\x87', '\x87', '\xA2', '\xA2', '\x1682', '\x1682', '\x2002', 
		'\x200C', '\x202A', '\x202B', '\x2031', '\x2031', '\x2061', '\x2061', 
		'\x3002', '\x3002', '\x2', '\xC3', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'K', '\x3', '\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'O', '\x3', '\x2', '\x2', '\x2', '\x3', 'R', '\x3', '\x2', 
		'\x2', '\x2', '\x5', 'V', '\x3', '\x2', '\x2', '\x2', '\a', '^', '\x3', 
		'\x2', '\x2', '\x2', '\t', '\x62', '\x3', '\x2', '\x2', '\x2', '\v', '\x64', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'i', '\x3', '\x2', '\x2', '\x2', '\x11', 'l', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'o', '\x3', '\x2', '\x2', '\x2', '\x15', 'r', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'u', '\x3', '\x2', '\x2', '\x2', '\x19', 'x', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '{', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x84', '\x3', '\x2', '\x2', '\x2', '#', '\x87', '\x3', '\x2', 
		'\x2', '\x2', '%', '\x8A', '\x3', '\x2', '\x2', '\x2', '\'', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', ')', '\x8F', '\x3', '\x2', '\x2', '\x2', '+', '\x92', 
		'\x3', '\x2', '\x2', '\x2', '-', '\x94', '\x3', '\x2', '\x2', '\x2', '/', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x31', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x35', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\xA4', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', ';', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '=', '\xAA', '\x3', '\x2', '\x2', '\x2', '?', '\xAC', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\xAE', '\x3', '\x2', '\x2', '\x2', '\x43', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'G', '\xB4', '\x3', '\x2', '\x2', '\x2', 'I', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', 'K', '\xB8', '\x3', '\x2', '\x2', '\x2', 'M', '\xBA', '\x3', '\x2', 
		'\x2', '\x2', 'O', '\xBC', '\x3', '\x2', '\x2', '\x2', 'Q', 'S', '\t', 
		'\x2', '\x2', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', 
		'\x2', '\x2', '\x2', 'U', '\x4', '\x3', '\x2', '\x2', '\x2', 'V', 'Z', 
		'\t', '\x3', '\x2', '\x2', 'W', 'Y', '\t', '\x4', '\x2', '\x2', 'X', 'W', 
		'\x3', '\x2', '\x2', '\x2', 'Y', '\\', '\x3', '\x2', '\x2', '\x2', 'Z', 
		'X', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', 
		'[', '\x6', '\x3', '\x2', '\x2', '\x2', '\\', 'Z', '\x3', '\x2', '\x2', 
		'\x2', ']', '_', '\n', '\x5', '\x2', '\x2', '^', ']', '\x3', '\x2', '\x2', 
		'\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\b', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x63', '\a', '\x66', '\x2', '\x2', '\x63', '\n', 
		'\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 'H', '\x2', '\x2', '\x65', 
		'\f', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', 'm', '\x2', '\x2', 
		'g', 'h', '\a', 'j', '\x2', '\x2', 'h', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'i', 'j', '\a', 'm', '\x2', '\x2', 'j', 'k', '\a', 'n', '\x2', '\x2', 
		'k', '\x10', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '\x66', '\x2', 
		'\x2', 'm', 'n', '\a', 'j', '\x2', '\x2', 'n', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\a', '\x66', '\x2', '\x2', 'p', 'q', '\a', 'n', '\x2', 
		'\x2', 'q', '\x14', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x63', 
		'\x2', '\x2', 's', 't', '\a', '\x66', '\x2', '\x2', 't', '\x16', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'v', '\a', '\x66', '\x2', '\x2', 'v', 'w', '\a', 
		'\x63', '\x2', '\x2', 'w', '\x18', '\x3', '\x2', '\x2', '\x2', 'x', 'y', 
		'\a', 't', '\x2', '\x2', 'y', 'z', '\a', 't', '\x2', '\x2', 'z', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '{', '|', '\a', 't', '\x2', '\x2', '|', '}', 
		'\a', 'q', '\x2', '\x2', '}', '\x1C', '\x3', '\x2', '\x2', '\x2', '~', 
		'\x7F', '\a', '#', '\x2', '\x2', '\x7F', '\x80', '\a', 'g', '\x2', '\x2', 
		'\x80', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\a', '#', 
		'\x2', '\x2', '\x82', '\x83', '\a', '\x65', '\x2', '\x2', '\x83', ' ', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '#', '\x2', '\x2', '\x85', 
		'\x86', '\a', 'r', '\x2', '\x2', '\x86', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x88', '\a', '\x65', '\x2', '\x2', '\x88', '\x89', '\a', 'u', 
		'\x2', '\x2', '\x89', '$', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', 
		'\a', 'h', '\x2', '\x2', '\x8B', '&', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', 'u', '\x2', '\x2', '\x8D', '\x8E', '\a', '\x63', '\x2', 
		'\x2', '\x8E', '(', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'u', '\x2', '\x2', '\x90', '\x91', '\a', '\x66', '\x2', '\x2', '\x91', 
		'*', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', '?', '\x2', '\x2', 
		'\x93', ',', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', '@', '\x2', 
		'\x2', '\x95', '.', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', 
		'>', '\x2', '\x2', '\x97', '\x30', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x99', '\a', '@', '\x2', '\x2', '\x99', '\x9A', '\a', '?', '\x2', '\x2', 
		'\x9A', '\x32', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '>', 
		'\x2', '\x2', '\x9C', '\x9D', '\a', '?', '\x2', '\x2', '\x9D', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', '#', '\x2', '\x2', '\x9F', 
		'\xA3', '\a', '?', '\x2', '\x2', '\xA0', '\xA1', '\a', '>', '\x2', '\x2', 
		'\xA1', '\xA3', '\a', '@', '\x2', '\x2', '\xA2', '\x9E', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA3', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\a', '}', '\x2', '\x2', '\xA5', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', '\x7F', '\x2', 
		'\x2', '\xA7', ':', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', 
		']', '\x2', '\x2', '\xA9', '<', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', 
		'\a', '_', '\x2', '\x2', '\xAB', '>', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAD', '\a', '.', '\x2', '\x2', '\xAD', '@', '\x3', '\x2', '\x2', '\x2', 
		'\xAE', '\xAF', '\a', '\x30', '\x2', '\x2', '\xAF', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\xB0', '\xB1', '\a', '*', '\x2', '\x2', '\xB1', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', '+', '\x2', '\x2', '\xB3', 
		'\x46', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', '-', '\x2', 
		'\x2', '\xB5', 'H', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', 
		'/', '\x2', '\x2', '\xB7', 'J', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', ',', '\x2', '\x2', '\xB9', 'L', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', '\x31', '\x2', '\x2', '\xBB', 'N', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBD', '\t', '\x6', '\x2', '\x2', '\xBD', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBF', '\b', '(', '\x2', '\x2', '\xBF', 
		'P', '\x3', '\x2', '\x2', '\x2', '\a', '\x2', 'T', 'Z', '`', '\xA2', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Dice.Grammar
